name: Patchwork
options:
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: "5.10"
    PRODUCT_BUNDLE_IDENTIFIER: ltd.ddga.patchwork
targets:
  Patchwork:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Patchwork
    settings:
      base:
        PRODUCT_NAME: Patchwork
        GENERATE_INFOPLIST_FILE: NO
        INFOPLIST_FILE: Patchwork/Info.plist
        MARKETING_VERSION: 3.2
        CURRENT_PROJECT_VERSION: 2
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_CFBundleIconName: AppIcon
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor

  PatchworkTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: PatchworkTests
    dependencies:
      - target: Patchwork
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ltd.ddga.patchwork.tests
        TEST_TARGET_NAME: Patchwork
        GENERATE_INFOPLIST_FILE: YES

  PatchworkUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: PatchworkUITests
    dependencies:
      - target: Patchwork
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ltd.ddga.patchwork.uitests
        TEST_TARGET_NAME: Patchwork
        GENERATE_INFOPLIST_FILE: YES

schemes:
  Patchwork:
    build:
      targets:
        Patchwork: all
        PatchworkTests: [test]
        PatchworkUITests: [test]
    test:
      config: Debug
      gatherCoverageData: false
      targets:
        - name: PatchworkTests
        - name: PatchworkUITests
    run:
      config: Debug
    archive:
      config: Release
